// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: greeter.sql

package db

import (
	"context"
)

const createGreeter = `-- name: CreateGreeter :one
INSERT INTO greeters (id, hello)
VALUES ($1, $2)
RETURNING id, hello, created_at
`

type CreateGreeterParams struct {
	ID    string `json:"id"`
	Hello string `json:"hello"`
}

func (q *Queries) CreateGreeter(ctx context.Context, arg CreateGreeterParams) (Greeter, error) {
	row := q.db.QueryRowContext(ctx, createGreeter, arg.ID, arg.Hello)
	var i Greeter
	err := row.Scan(&i.ID, &i.Hello, &i.CreatedAt)
	return i, err
}

const getGreeter = `-- name: GetGreeter :one
SELECT id, hello, created_at FROM greeters
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGreeter(ctx context.Context, id string) (Greeter, error) {
	row := q.db.QueryRowContext(ctx, getGreeter, id)
	var i Greeter
	err := row.Scan(&i.ID, &i.Hello, &i.CreatedAt)
	return i, err
}

const listGreeter = `-- name: ListGreeter :many
SELECT id, hello, created_at FROM greeters
ORDER BY created_at DESC
`

func (q *Queries) ListGreeter(ctx context.Context) ([]Greeter, error) {
	rows, err := q.db.QueryContext(ctx, listGreeter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Greeter{}
	for rows.Next() {
		var i Greeter
		if err := rows.Scan(&i.ID, &i.Hello, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
