// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Greeter struct {
	ID        string       `json:"id"`
	Hello     string       `json:"hello"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type OutboxEvent struct {
	ID        uuid.UUID `json:"id"`
	Topic     string    `json:"topic"`
	Payload   []byte    `json:"payload"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}
