// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, topic, payload
FROM service_boilerplate_outbox_events
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetPendingOutboxEventsRow struct {
	ID      uuid.UUID `json:"id"`
	Topic   string    `json:"topic"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]GetPendingOutboxEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingOutboxEventsRow{}
	for rows.Next() {
		var i GetPendingOutboxEventsRow
		if err := rows.Scan(&i.ID, &i.Topic, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO service_boilerplate_outbox_events (topic, payload, status)
VALUES ($1, $2, 'PENDING')
`

type InsertOutboxEventParams struct {
	Topic   string `json:"topic"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxEvent, arg.Topic, arg.Payload)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE service_boilerplate_outbox_events 
SET status = 'PUBLISHED' 
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventPublished, id)
	return err
}
