// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateGreeter(ctx context.Context, arg CreateGreeterParams) (Greeter, error)
	GetGreeter(ctx context.Context, id string) (Greeter, error)
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]GetPendingOutboxEventsRow, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListGreeter(ctx context.Context) ([]Greeter, error)
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
