// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"service_boilerplate/internal/biz"
	"service_boilerplate/internal/conf"
	"service_boilerplate/internal/data"
	"service_boilerplate/internal/server"
	"service_boilerplate/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	producer, cleanup2, err := data.NewNSQProducer(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	greeterEventPublisher, err := data.NewNSQPublisher(confData, dataData, producer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, greeterEventPublisher, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	nsqServer, err := server.NewNSQServer(confData, greeterService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	outboxRepo := data.NewOutboxRepo(dataData, logger)
	outboxRelayServer := server.NewOutboxRelayServer(outboxRepo, producer, logger)
	app := newApp(logger, grpcServer, httpServer, nsqServer, outboxRelayServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
